language: scala
scala:
  - 2.12.1
jdk:
  - openjdk8
sudo: false
script:
  - sbt test transferPublishAndTagResources
  - scripts/publishAndTag 'slamdata/scala-xml-names'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
